### ISSUE TITLE
 qdnaseq.R script  not find

### ISSUE THREAD

**Issue by zhangyafeng1** [gerstung-lab/BarrettsProgressionRisk#1]
hello :
For the "Example Usage for Predicting Barrett's Progression " part , said that ”Using your own data and the qdnaseq.R script found in the example/ directory first process one or more BAM files from a single patient and output the files into a unique directory" ,.

But when I downloaded it, I didn't find the   qdnaseq.R script in the example directory, could you help me ? 
Thank you very much

**Comment by skillcoyne** [comment]
My apologies, the README had some old information in it.  I've updated it, but the QDNAseq usage is simple (see README). The function will output to the 'outputPath' the raw and fitted files required for subsequent processing.

**Comment by zhangyafeng1** [comment]
I am sorry , In the sample code “library(BarrettsProgressionRisk)“ ， I could not find “BarrettsProgressionRisk” package in all the directories。
I am a novice, could you tell me the reason？ Thank you !

**Comment by skillcoyne** [comment]
You have to build and install the package after cloning the source or
downloading the release. Note this is R source code:
R CMD build BarrettsProgressionRisk/
R CMD INSTALL BarrettsProgressionRisk_1.0.tar.gz

https://github.com/gerstung-lab/BarrettsProgressionRisk/releases/tag/v1.0

**Comment by zhangyafeng1** [comment]
hi  skillcoyne:
 
![image](https://user-images.githubusercontent.com/52239895/93196734-61159b00-f77d-11ea-912d-8cc800b07e2a.png)

when I install the package, An error has occurred 。 Is it  need me to install these packages ? Thank you very much !
